# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Angular Package

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install Angular CLI globally
      # - run: npm install -g @angular/cli
      # Install project dependencies
      - run: npm ci
      # Build the Angular project
      - run: npm run build
      # Run Angular tests
      # - run: ng test --watch=false --browsers=ChromeHeadless

      - name: Upload Build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-artifact
          path: dist
          retention-days: 2
