# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Angular Package

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Install Angular CLI globally
      - run: npm install -g @angular/cli
      # Install project dependencies
      - run: npm ci
      # Build the Angular project
      - run: ng build --output-path=dist --base-href /deenijob-frontend/
      # Run Angular tests
      # - run: ng test --watch=false --browsers=ChromeHeadless

      - name: Upload Build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: build-artifact
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write    # Grant access to GitHub Pages
      id-token: write # Enable OIDC token for GitHub Pages

    steps:
      # Step 7: Checkout the code again
      - uses: actions/checkout@v4

      # Step 8: Deploy to GitHub Pages using the artifact
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist  # Folder to deploy (Angular's `dist` folder)